### ISSUE TITLE
Compiled file placed in incorrect location when using coconut --watch

### ISSUE THREAD

**Issue by dileep-kishore** [evhub/coconut#333]
`coconut -pswt 36 mind-src mind` command on initial run compiles files to the correct location (mind/main/otu/OtuClass.py).
```CoconutWarning: extraneous --package argument passed; --mypy implies --package
Left unchanged    mind/__init__.py (pass --force to override).
Left unchanged    mind/utils/__init__.py (pass --force to override).
Left unchanged    mind/utils/data_conversion/__init__.py (pass --force to override).
Left unchanged    mind/utils/data_conversion/CooccurNet.py (pass --force to override).
Left unchanged    mind/utils/data_validation/__init__.py (pass --force to override).
Left unchanged    mind/utils/data_validation/ValidOtu.py (pass --force to override).
Left unchanged    mind/utils/data_validation/OtuValidator.py (pass --force to override).
Left unchanged    mind/main/__init__.py (pass --force to override).
Left unchanged    mind/main/otu/__init__.py (pass --force to override).
Compiling         mind-src/main/otu/OtuClass.coco ...
Compiled to       mind/main/otu/OtuClass.py .
mind/main/otu/OtuClass.py:318: error: non-default argument follows default argument
```

On file change - the compiled `.py` file is placed in the wrong location (mind/OtuClass.py).
```Watching          mind-src (press Ctrl-C to end)...
Compiling         mind-src/main/otu/OtuClass.coco ...
Compiled to       mind/OtuClass.py .
mind/OtuClass.py:318: error: non-default argument follows default argument
```

Using `Coconut: Version 1.3.0 [Dead Parrot] running on Python 3.6.2`

**Comment by evhub** [comment]
@dileep-kishore This should now be fixed on `coconut-develop`! Just `pip install coconut-develop` to get the fix.

**Comment by dileep-kishore** [comment]
Tried this again on `Coconut: Version 1.3.0-post_dev3 [Dead Parrot] running on Python 3.6.2`

The bug still persists:
```
Compiling         mind-src/main/otu/OtuClass.coco ...
Compiled to       mind/OtuClass.py .
```

**Comment by dileep-kishore** [comment]
Thanks! Just tried it and it works now.
