### ISSUE TITLE
Cannot name a class "Counter"

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#396]
```
D:\Arne\projects\sos>coconut x.coco --mypy
Compiling         x.coco ...
Compiled to       x.py .
x.py:14: error: Incompatible import of "Counter" (imported name has type "Type[Counter[Any]]", local name has type "Type[Counter]")
Exiting due to MyPy error.
```
for
```
class Counter()
```

**Comment by ArneBachmann** [comment]
In my case it´s
`error: Incompatible import of "Counter" (imported name has type "Type[collections.Counter[Any]]", local name has type "Type[sos.utility.Counter[Any]]")`

**Comment by evhub** [comment]
Resolved by #403.

**Comment by ArneBachmann** [comment]
Maybe I'm using the typing library wrongly, but I still get my error:
```
if TYPE_CHECKING:
  from typing import *
  Number = TypeVar("Number", int, float)
  class Counter(Generic[Number])
else:
  class Counter()
```
Does anybody know how to implement a type-restricted class (all methods use int for int-typed class, or all methods use float for a float-typed class)?

**Comment by evhub** [comment]
@ArneBachmann The problem is that you're doing `from typing import *`, which imports `typing.Counter`, and then you override it. You can't do that. Instead, you need to only import the names from `typing` that you're actually using.

**Comment by ArneBachmann** [comment]
Got it. But wouldn´t it be cool if Coconut automatically detected the types I use and imports them silently, like some versions before?
