### ISSUE TITLE
`imp` DeprecationWarning

### ISSUE THREAD

**Issue by khayyamsaleem** [evhub/coconut#442]
The `imp` module is deprecated in favour of importlib, but it's imported as part of the standard compilation routine.

**Comment by evhub** [comment]
@khayyamsaleem Should now be fixed in `coconut-develop`. Just `pip install coconut-develop` to get the fix.

**Comment by Nexus6** [comment]
I just fired up coconut for the first time in a long time and I'm running into this problem.  I installed coconut and coconut-develop and compiled a small example program with
$ coconut -t36 ./main.coco

In the newly-created main.py I see near the top
 
```
# Compiled with Coconut version 1.3.1-post_dev28 [Dead Parrot]
class _coconut:
    import collections, copy, functools, imp, itertools, operator, types, weakref
```

Have I done something wrong here?

**Comment by evhub** [comment]
@Nexus6 The fix to this issue was implemented in `dev29`, but your header indicates you're running `dev28`.

**Comment by ArneBachmann** [comment]
Yes, but v28 is the latest version published on pypi.org

**Comment by evhub** [comment]
Ah, I see. There was a problem with the automatic PyPI upload. Should be fixed now.

**Comment by Nexus6** [comment]
After doing a "pip install --upgrade coconut coconut-develop" I'm still getting

```
$ coconut --version
Coconut: Version 1.3.1-post_dev28 [Dead Parrot] running on Python 3.5.2

```
It appears that the deprecated import is still being generated, but one thing that I noticed is that despite this, I don't get a deprecation warning under python3.5 but I do under python3.7.

**Comment by evhub** [comment]
@Nexus6 You were just a little bit too fast. PyPI just updated to `dev29` right now.

**Comment by Nexus6** [comment]
Right you are, I've got dev29 now and the problem seems to be gone.  Thanks!  Q: when doing the pip --upgrade of coconut and coconut-develop, I saw the following message
`coconut-develop 1.3.1.post0.dev29 has requirement prompt-toolkit<.2,>=1; python_version >= "2.7", but you'll have prompt-toolkit 2.0.4 which is incompatible.`

... however the install completed successfully and the compiler seems to be happy with its environment.  Is the message anything to worry about?

**Comment by evhub** [comment]
@Nexus6 It means you won't get syntax highlighting in the interpreter. You'll have to downgrade your `prompt-toolkit` to get that. I would just upgrade Coconut to the newest `promp-toolkit`, but ipython/jupyter haven't upgraded to the new one yet and I don't want to be incompatible with them.

**Comment by evhub** [comment]
Maybe I should just add some universal compatibility support for `prompt-toolkit` 1 or 2. That's probably worthy of a separate issue.
