### ISSUE TITLE
Separate coconut kernel installation and `nb_conda_kernel` support

### ISSUE THREAD

**Issue by tbsexton** [evhub/coconut#540]
Using [`nb_conda_kernels`](https://github.com/Anaconda-Platform/nb_conda_kernels) as my primary workflow (i.e. not needing a separate jupyter notebook server running for every kernel, just installing a kernel in each environment with one central environment running the server) I would

1. install jupyter, nb_conda_kernels, etc in the main/base/default environment, and run jupyter.
2. install ipykernel, project dependencies, etc in a project-specific environment. 
3. open jupyter interface, and switch kernel. Not to "python 3", etc, but to `Python [conda env:projectenvname]` which gives me all of my packages/dependencies needed for that project, still on the one jupyter server. 

My question revolves around using coconut within this workflow (which is becoming more standard in teaching/academic circles afaik). I have coconut[all] installed in both the main and the "cocotest" project environment, and have run `coconut --jupyter` successfully in both as well. But I still cannot access coconut syntax directly (i.e. no magic functions) within a notebook using the `Python [conda env:cocotest]` kernel. Given that `nb_conda_kernels` explicitly supports other languages (ipykernel,  r-irkernel, anything on that [list of languages](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels) above) as long as the kernel is installed inside that environment, i don't really understand why coconut isn't working?

I did also try running `coconut --jupyter notebook` from the main environment, and selecting the `Python [conda env:cocotest]` kernel, but still no dice. 

I think one solution is to either make a separate installable or maybe optional `coconut[kernel]` installation that will act like ipykernel, so that users can add coconut support in jupyter to their versioned dependency list (e.g. `environment.yml`, etc), just like they can now with `ipykernel` and `r-irkernel`, while only needing to run a single jupyter server at any given time.

**Comment by evhub** [comment]
@tbsexton This should now be fixed on develop along with #281.

**Comment by tbsexton** [comment]
Awesome, so what is the preferred order of operations now? Is there a way to enable nb_conda_kernels to detect a coconut kernel within an environment, given only the pip install?

(I install coconut under a -pip: coconut heading for exactly that in the .yml file, thanks!)

**Comment by tbsexton** [comment]
@evhub Actually I'm still having some issues. 

1. Installing via `pip install conda-develop[all]` after removing the old coconut installation leads to  an error unless i manually update setuptools in every conda environment (even if I start with a fresh one) 
   > ```RuntimeError: bdist_wheel not supported for setuptools versions < 18 (run 'pip install --upgrade setuptools' to fix)```

   Can this version of setuptools be added as a dependency? 

2. Installing `conda-develop[all]` in the base environment (where nb_conda_kernels lives) and in the testing environment (where other kernels live), and then even running `coconut --jupyter` inside both, still does not allow me to select the testing environment and have access to coconut syntax like with other language kernels. 

   **expected**: running `coconut --jupyter notebook` (or in theory just `jupyter notebook`) in the base environment should allow me to select a `Coconut [conda env:PROJECT]` kernel in the notebook interface. This would reflect typical interactions with other kernels (see Python and R kernels at the bottom of the menu). 
![image](https://user-images.githubusercontent.com/12550525/81697250-e76a4b00-9432-11ea-951c-43559eeb4512.png)

**Comment by evhub** [comment]
@tbsexton Try again with `pip install -U coconut-develop>=1.4.3-post_dev25` and I suspect it'll work this time.

**Comment by tbsexton** [comment]
@evhub Can confirm, it's working! This is fantastic, and really helps preserve development pipelines with the rest of my non-coconut-based  team (e.g. using poetry+conda).

 Able to run vanilla jupyter notebook in an environment that has `nb_conda_kernels`, and as long as the "project" environment has that version of coconut and ipykernel installed, the notebook server can successfully find/run `Coconut [conda env:project]`. 

The setuptools fix worked, btw! 

Also, just a note that *not* having `ipykernel` as a dependency in the project environment will get the server stuck in an infinite loop, looking for "jupyter" that is missing. Not sure that's something worth fixing, but just a heads up that the automatic coconut kernel install is assuming jupyter is there, which it may not always be. Don't know the proper solution here, since other languages (e.g. R) don't have a hard dependency on `ipykernel` that coconut needs, for obvious reasons. But those not wanting jupyter/ipython support dont really need to have that extra dependency bog down their install, so I'm not sure. 

Thanks again, this is huge!

**Comment by evhub** [comment]
@tbsexton Great—glad it's working for you! As for installing `ipykernel`, if you just install `coconut-develop[jupyter]` it should take care of that for you.

**Comment by fabianhjr** [comment]
> Installing via pip install conda-develop[all] after removing the old coconut installation leads to an error unless i manually update setuptools in every conda environment (even if I start with a fresh one)
>
>    RuntimeError: bdist_wheel not supported for setuptools versions < 18 (run 'pip install --upgrade setuptools' to fix)
>
> Can this version of setuptools be added as a dependency?

This might have been related to #560
